name: Android CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, Test, and Sign APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > release.keystore

    - name: Clean project
      run: |
        chmod +x app/gradlew
        cd app
        ./gradlew clean

    - name: Build and test
      run: |
        chmod +x app/gradlew
        cd app
        ./gradlew assembleRelease || exit 1
        ./gradlew test || exit 1
      env:
        KEYSTORE_FILE_PATH: ${{ github.workspace }}/release.keystore
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload signed APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
